import { Template } from "./types";
import { DEFAULT_VALUE_FORMAT } from "./valueFormat";
import {
  GDP_SAMPLE,
  FOOTBALL_SAMPLE,
  POPULATION_SAMPLE,
  NBA_SAMPLE,
  CRYPTO_SAMPLE,
  COMPANIES_SAMPLE,
  YOUTUBE_SAMPLE,
  OLYMPICS_SAMPLE,
  F1_SAMPLE,
  STREAMING_SAMPLE,
  MILITARY_SAMPLE,
} from "./sampleData";

export const TEMPLATES: Template[] = [
  {
    id: "viral-bar-race",
    name: "Viral Bar Race",
    description: "GDP race between world economies — perfect for viral content",
    icon: "🏆",
    type: "bar_race",
    data: GDP_SAMPLE,
    settings: {
      title: "Top Economies by GDP",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "educational-timeline",
    name: "Educational Timeline",
    description: "Population growth data — great for educational content",
    icon: "📚",
    type: "bar_race",
    data: POPULATION_SAMPLE,
    settings: {
      title: "World Population Growth",
      theme: "light",
      speed: "slow",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "sports-battle",
    name: "Sports Battle",
    description: "All-time football goal scorers racing for the top",
    icon: "⚽",
    type: "bar_race",
    data: FOOTBALL_SAMPLE,
    settings: {
      title: "All-Time Goal Scorers",
      theme: "neon",
      speed: "fast",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "economic-growth",
    name: "Economic Growth",
    description: "Compare economic powerhouses over the decades",
    icon: "📈",
    type: "bar_race",
    data: GDP_SAMPLE,
    settings: {
      title: "Economic Powerhouses",
      theme: "dark",
      speed: "slow",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "timeline-population",
    name: "Population Timeline",
    description: "Watch population milestones unfold through history",
    icon: "🕰️",
    type: "timeline",
    data: POPULATION_SAMPLE,
    settings: {
      title: "World Population Milestones",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "top10-gdp",
    name: "Top 10 Economies",
    description: "Countdown revealing the world's biggest economies",
    icon: "🏅",
    type: "top10",
    data: GDP_SAMPLE,
    settings: {
      title: "Top 10 Economies by GDP",
      theme: "neon",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "comparison-football",
    name: "Goal Scorer Battle",
    description: "Head-to-head showdown between legendary strikers",
    icon: "⚔️",
    type: "comparison",
    data: FOOTBALL_SAMPLE,
    settings: {
      title: "Ronaldo vs Messi",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
];

TEMPLATES.push(
  {
    id: "nba-ranking",
    name: "NBA Scoring Race",
    description: "All-time NBA scoring leaders race — LeBron, Kareem, Jordan",
    icon: "🏀",
    type: "bar_race",
    data: NBA_SAMPLE,
    settings: {
      title: "NBA All-Time Scoring Leaders",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "crypto-race",
    name: "Crypto Market Cap Race",
    description: "Top cryptocurrencies racing by market cap",
    icon: "🪙",
    type: "bar_race",
    data: CRYPTO_SAMPLE,
    settings: {
      title: "Top Crypto by Market Cap",
      theme: "neon",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "companies-marketcap",
    name: "Richest Companies",
    description: "Most valuable companies by market cap over time",
    icon: "💼",
    type: "bar_race",
    data: COMPANIES_SAMPLE,
    settings: {
      title: "Most Valuable Companies",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "top10-crypto",
    name: "Top 10 Crypto",
    description: "Countdown of the top 10 cryptocurrencies",
    icon: "🥇",
    type: "top10",
    data: CRYPTO_SAMPLE,
    settings: {
      title: "Top 10 Crypto by Market Cap",
      theme: "neon",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
);

TEMPLATES.push(
  {
    id: "youtube-subscribers",
    name: "YouTube Subscribers Race",
    description: "Biggest YouTube channels racing for the most subscribers",
    icon: "📺",
    type: "bar_race",
    data: YOUTUBE_SAMPLE,
    settings: {
      title: "Most Subscribed YouTube Channels",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "olympics-medals",
    name: "Olympic Medal Race",
    description: "All-time Olympic medal tally across countries",
    icon: "🥇",
    type: "bar_race",
    data: OLYMPICS_SAMPLE,
    settings: {
      title: "Olympic All-Time Medal Tally",
      theme: "light",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "f1-champions",
    name: "F1 World Champions",
    description: "Formula 1 drivers and their championship titles",
    icon: "🏎️",
    type: "bar_race",
    data: F1_SAMPLE,
    settings: {
      title: "F1 World Championship Titles",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "streaming-subs",
    name: "Streaming Wars",
    description: "Netflix, Disney+, Prime — streaming subscriber race",
    icon: "🎬",
    type: "bar_race",
    data: STREAMING_SAMPLE,
    settings: {
      title: "Streaming Subscriber Race",
      theme: "neon",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "military-spending",
    name: "Military Spending Race",
    description: "Top countries by defense budget across the decade",
    icon: "🛡️",
    type: "bar_race",
    data: MILITARY_SAMPLE,
    settings: {
      title: "Top Military Spending by Country",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "top10-companies",
    name: "Top 10 Companies",
    description: "Countdown of the most valuable companies in the world",
    icon: "💰",
    type: "top10",
    data: COMPANIES_SAMPLE,
    settings: {
      title: "Top 10 Most Valuable Companies",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "comparison-f1",
    name: "Hamilton vs Verstappen",
    description: "Head-to-head F1 championship comparison",
    icon: "⚔️",
    type: "comparison",
    data: F1_SAMPLE,
    settings: {
      title: "Hamilton vs Verstappen",
      theme: "neon",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
  {
    id: "timeline-youtube",
    name: "YouTube Growth Timeline",
    description: "Watch the biggest channels grow year by year",
    icon: "📈",
    type: "timeline",
    data: YOUTUBE_SAMPLE,
    settings: {
      title: "YouTube Channel Growth",
      theme: "dark",
      speed: "medium",
      showLabels: true,
      showValues: true,
      showIntro: true,
      smoothAnimation: true,
    },
  },
);
