export type BlogCategory =
  | "Tutorials"
  | "TikTok Growth"
  | "YouTube Shorts"
  | "Data Visualization"
  | "Football Statistics"
  | "Viral Video Psychology"
  | "Creator Economy"
  | "Case Studies";

export const BLOG_CATEGORIES: BlogCategory[] = [
  "Tutorials",
  "TikTok Growth",
  "YouTube Shorts",
  "Data Visualization",
  "Football Statistics",
  "Viral Video Psychology",
  "Creator Economy",
  "Case Studies",
];

export interface Author {
  name: string;
  role: string;
  bio: string;
}

export const AUTHORS: Record<string, Author> = {
  editorial: {
    name: "Data to Video Editorial",
    role: "Editorial team",
    bio: "We test every format we write about. Our editorial team publishes data videos daily across niche TikTok and YouTube accounts and shares what actually moves the needle for creators.",
  },
  marco: {
    name: "Marco Rivers",
    role: "Football data creator",
    bio: "Marco runs a football-stats account that crossed 600k followers in 14 months posting one animated chart per day. He focuses on the European leagues and Champions League history.",
  },
  ana: {
    name: "Ana Petrova",
    role: "Growth analyst",
    bio: "Ana studies algorithmic distribution on short-form platforms and consults for finance and education channels on TikTok and YouTube Shorts.",
  },
};

export type BodyBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string; id?: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[]; ordered?: boolean }
  | { type: "callout"; text: string; tone?: "tip" | "warn" }
  | { type: "quote"; text: string; cite?: string }
  | { type: "embed"; kind: "template" | "dataset" | "tool" | "watch"; slug: string; label?: string };

export interface FaqItem { q: string; a: string }

export interface BlogPost {
  slug: string;
  title: string;
  seoTitle: string;
  excerpt: string;
  date: string;
  updated?: string;
  readMinutes: number;
  category: BlogCategory;
  tags: string[];
  authorKey: keyof typeof AUTHORS;
  body: BodyBlock[];
  faqs?: FaqItem[];
  related: string[];
  relatedTemplates?: string[];
  relatedDatasets?: string[];
  relatedTools?: string[];
  relatedWatch?: string[];
  ogImage?: string;
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "how-to-make-viral-bar-chart-race-videos",
    title: "How to Make Viral Bar Chart Race Videos in 2026",
    seoTitle: "How to Make Viral Bar Chart Race Videos — Step-by-Step Guide",
    excerpt: "A practical guide to producing bar chart race videos that consistently break 100k views on TikTok and YouTube Shorts.",
    date: "2026-05-10",
    updated: "2026-05-18",
    readMinutes: 6,
    category: "Tutorials",
    tags: ["bar chart race", "tiktok", "tutorial", "viral"],
    authorKey: "editorial",
    body: [
      { type: "p", text: "Bar chart races have quietly become one of the most reliable formats in short-form video. The reason is simple: humans can't stop watching a leaderboard shift. If you've ever scrolled past a 'Top countries by GDP from 1960 to 2025' clip and ended up watching the whole 45 seconds, you already understand the magic. This guide walks through exactly how to make those videos — repeatably, and with data you choose." },
      { type: "h2", text: "Step 1: Pick a topic with built-in tension" },
      { type: "p", text: "The viral bar chart races all share one thing: an obvious rivalry. China vs the US. Ronaldo vs Messi. Bitcoin vs Ethereum. The reorder animation only works when viewers care which bar is on top. Before you touch any tool, write down the two or three categories your audience already argues about. That's your dataset." },
      { type: "callout", tone: "tip", text: "If you can't name the rivalry in five words, the video won't hook. Test the title out loud before you build." },
      { type: "h2", text: "Step 2: Get clean time-series data" },
      { type: "p", text: "Bar chart races need values across time. The minimum useful structure is a CSV with one label column (country, player, coin) and one numeric column per time step (year, quarter, season). World Bank, Wikipedia, Statista and FBref all publish data that drops straight into this shape." },
      { type: "embed", kind: "dataset", slug: "gdp-countries", label: "Use our pre-cleaned GDP by Country dataset" },
      { type: "h2", text: "Step 3: Render in Data to Video" },
      { type: "p", text: "Open the bar chart race template, paste your CSV, pick a dark or neon theme, and add a hook title. A great hook is short and confrontational — 'The country that quietly overtook the US' beats 'GDP growth 1960–2025' every time." },
      { type: "embed", kind: "template", slug: "bar-chart-race" },
      { type: "h2", text: "Step 4: Export vertical" },
      { type: "p", text: "Export at 1080×1920. Horizontal exports get half the reach on TikTok and Reels. Add captions in your editor of choice, or use the built-in viral hook overlay." },
      { type: "h2", text: "Step 5: Post a series, not a one-off" },
      { type: "p", text: "The accounts that grow fastest with bar chart races post daily. Each video uses the same template, same theme, same hook structure — different data. That's how you get the algorithm to learn your channel." },
      { type: "h3", text: "A weekly publishing cadence that works" },
      { type: "list", ordered: true, items: [
        "Monday: Top 10 countdown (richest, biggest, fastest)",
        "Wednesday: Bar chart race over time (decades, seasons)",
        "Friday: Head-to-head comparison (rivalry of the week)",
        "Sunday: Recap reel collaging the week's best stat",
      ] },
    ],
    faqs: [
      { q: "How long should a bar chart race be?", a: "Between 20 and 45 seconds for TikTok and Reels. Anything longer loses retention; anything shorter doesn't give the reorder time to register." },
      { q: "Do I need a paid subscription to remove the watermark?", a: "Free exports include a small Data to Video tag. Premium exports are watermark-free." },
      { q: "What CSV format works?", a: "Wide format: one label column, then one numeric column per time step. Strip currency symbols and commas first." },
    ],
    related: ["why-bar-chart-races-go-viral", "best-tiktok-data-visualization-ideas"],
    relatedTemplates: ["bar-chart-race", "gdp-race", "top-10"],
    relatedDatasets: ["gdp-countries", "fifa-goals"],
    relatedTools: ["chart-race-generator", "csv-to-video"],
    relatedWatch: ["gdp-race-usa-vs-china"],
    ogImage: "/og/blog-bar-chart-race.jpg",
  },
  {
    slug: "best-tiktok-data-visualization-ideas",
    title: "20 Best TikTok Data Visualization Ideas for Creators",
    seoTitle: "Best TikTok Data Visualization Ideas — 20 Viral Formats",
    excerpt: "Twenty proven data video concepts that get millions of views on TikTok, with the exact template to use for each.",
    date: "2026-04-22",
    readMinutes: 7,
    category: "TikTok Growth",
    tags: ["tiktok", "ideas", "data visualization"],
    authorKey: "ana",
    body: [
      { type: "p", text: "If you make data content on TikTok and your views have plateaued, the issue is almost always the format — not the data. Below are twenty concepts that consistently outperform, grouped by the Data to Video template that fits each." },
      { type: "h2", text: "Bar chart race ideas" },
      { type: "list", ordered: true, items: [
        "Top economies by GDP from 1980",
        "All-time men's football goal scorers",
        "Biggest YouTubers by subscriber count",
        "Crypto market caps month by month",
        "Most-downloaded apps of the decade",
        "Most-streamed songs since Spotify launched",
        "F1 driver championship points by season",
        "Summer Olympic medal counts by country",
      ] },
      { type: "embed", kind: "template", slug: "bar-chart-race" },
      { type: "h2", text: "Top 10 countdown ideas" },
      { type: "list", ordered: true, items: [
        "Richest people in the world right now",
        "Best-selling video games of all time",
        "Most-followed celebrities on Instagram",
        "Most expensive football transfers ever",
        "Largest cities by population in 2025",
      ] },
      { type: "embed", kind: "template", slug: "top-10" },
      { type: "h2", text: "Timeline ideas" },
      { type: "list", ordered: true, items: [
        "World population from year 1 to 2025",
        "Major wars by death toll over centuries",
        "Big-tech company founding years",
        "Average global temperature 1880 → today",
      ] },
      { type: "embed", kind: "template", slug: "population-growth" },
      { type: "h2", text: "Head-to-head comparison ideas" },
      { type: "list", ordered: true, items: [
        "Ronaldo vs Messi — career goals",
        "iPhone vs Android market share over time",
        "PlayStation vs Xbox lifetime sales",
      ] },
      { type: "embed", kind: "template", slug: "football-stats" },
      { type: "p", text: "Pick one, open the matching template, and publish today. The accounts that win in this niche publish daily — the data is everywhere." },
    ],
    faqs: [
      { q: "Which idea should I start with?", a: "Pick the one closest to your existing audience. Football accounts should start with scorer leaderboards; finance accounts with GDP or market cap races." },
    ],
    related: ["how-to-make-viral-bar-chart-race-videos", "how-football-channels-use-statistics-videos"],
    relatedTemplates: ["bar-chart-race", "top-10", "population-growth", "football-stats"],
    relatedDatasets: ["gdp-countries", "fifa-goals", "nba-points"],
    ogImage: "/og/blog-tiktok-ideas.jpg",
  },
  {
    slug: "how-football-channels-use-statistics-videos",
    title: "How Football Channels Use Statistics Videos to Hit Millions of Views",
    seoTitle: "How Football Channels Use Stats Videos — Viral Format Breakdown",
    excerpt: "A breakdown of the stats video formats top football creators use — and how to replicate them with free tools.",
    date: "2026-04-01",
    readMinutes: 5,
    category: "Football Statistics",
    tags: ["football", "case study", "stats"],
    authorKey: "marco",
    body: [
      { type: "p", text: "Open TikTok and search 'football stats'. The top results aren't from clubs or broadcasters — they're from one-person channels publishing simple animated charts every single day. The format is so reliable that several accounts have crossed a million followers in under a year doing nothing else." },
      { type: "h2", text: "The three core formats" },
      { type: "p", text: "Football stats channels rotate between three formats: head-to-head comparisons, all-time leaderboards and season-by-season races. Each takes under five minutes to make once you have a template." },
      { type: "embed", kind: "watch", slug: "ronaldo-vs-messi-goals" },
      { type: "h2", text: "Where to get the data" },
      { type: "p", text: "FBref, Transfermarkt and Wikipedia cover almost every stat worth animating. Copy a table, paste into Google Sheets, export as CSV, drop into Data to Video." },
      { type: "embed", kind: "dataset", slug: "fifa-goals" },
      { type: "h2", text: "What makes them work" },
      { type: "list", items: [
        "Confrontational title — 'Who's actually the GOAT?' beats 'Comparison'",
        "Fast pacing — under 25 seconds end-to-end",
        "Clear winner reveal in the final 3 seconds",
        "Familiar player faces as avatars",
      ] },
      { type: "quote", text: "Posting daily is the cheat code. The algorithm rewards consistency in this niche more than any other I've worked in.", cite: "Marco" },
    ],
    faqs: [
      { q: "How often should I post?", a: "Daily. The football stats niche moves fast and rewards consistency more than production value." },
      { q: "Do I need official data?", a: "No — FBref, Transfermarkt and Wikipedia are accurate enough for short-form content as long as you credit them." },
    ],
    related: ["how-to-make-viral-bar-chart-race-videos", "best-tiktok-data-visualization-ideas"],
    relatedTemplates: ["football-stats", "bar-chart-race", "nba-ranking-animation"],
    relatedDatasets: ["fifa-goals", "nba-points"],
    relatedWatch: ["ronaldo-vs-messi-goals"],
    ogImage: "/og/blog-football-stats.jpg",
  },
  {
    slug: "why-bar-chart-races-go-viral",
    title: "Why Bar Chart Races Go Viral (and How to Engineer the Effect)",
    seoTitle: "Why Bar Chart Races Go Viral — The Psychology Behind the Format",
    excerpt: "The cognitive reasons behind the bar chart race's enduring viral pull — and how to design your videos around them.",
    date: "2026-03-15",
    readMinutes: 5,
    category: "Viral Video Psychology",
    tags: ["psychology", "viral", "bar chart race"],
    authorKey: "ana",
    body: [
      { type: "p", text: "Bar chart races have been viral for almost a decade. That kind of longevity is rare in short-form video, and it's not an accident — the format taps directly into how human attention works." },
      { type: "h2", text: "Open loops" },
      { type: "p", text: "Every reorder of the bars creates a tiny open loop in the viewer's mind: who's going to be on top next? The brain refuses to close that loop until the animation ends, which is why people watch all the way through." },
      { type: "h2", text: "Recognizable categories" },
      { type: "p", text: "Countries, players and brands are pre-cached in everyone's head. Viewers don't need to read labels — they recognize the bars instantly, which removes friction in the first three seconds." },
      { type: "h2", text: "Compressed time" },
      { type: "p", text: "Sixty years of GDP in thirty seconds feels like watching history on fast-forward. That compression is intrinsically pleasurable." },
      { type: "h2", text: "Designing for the effect" },
      { type: "list", items: [
        "Keep the bar count between 5 and 10",
        "Use bold colors that contrast against a dark background",
        "Add a hook title in the first frame",
        "Don't slow the animation down — fast pacing is part of the appeal",
      ] },
      { type: "embed", kind: "tool", slug: "chart-race-generator" },
    ],
    faqs: [
      { q: "Does the same psychology apply to Top 10 countdowns?", a: "Yes — the open-loop effect is even stronger because the brain explicitly waits for #1." },
    ],
    related: ["how-to-make-viral-bar-chart-race-videos", "best-data-formats-for-animated-videos"],
    relatedTemplates: ["bar-chart-race", "top-10"],
    relatedTools: ["chart-race-generator"],
    ogImage: "/og/blog-why-viral.jpg",
  },
  {
    slug: "best-data-formats-for-animated-videos",
    title: "Best Data Formats for Animated Videos",
    seoTitle: "Best Data Formats for Animated Videos — CSV, JSON and Beyond",
    excerpt: "Which data structures work best for animated charts, and how to clean your data before importing it.",
    date: "2026-02-28",
    readMinutes: 4,
    category: "Data Visualization",
    tags: ["csv", "data", "tutorial"],
    authorKey: "editorial",
    body: [
      { type: "p", text: "The single biggest reason animated chart videos fail is bad data. Not wrong data — badly shaped data. Here's how to prep yours so it drops cleanly into any animated chart tool." },
      { type: "h2", text: "CSV is king" },
      { type: "p", text: "Use a flat CSV with one label column and one numeric column per time step. Avoid merged cells, footnotes inside numeric cells, and currency symbols mixed with numbers." },
      { type: "h2", text: "Time as columns, not rows" },
      { type: "p", text: "For bar chart races, each time step (year, month, season) should be its own column. Each row is one category. This 'wide' format is what every animation engine expects." },
      { type: "h2", text: "Five to ten rows" },
      { type: "p", text: "Bar chart races with more than ten bars are unreadable on a phone. Pre-filter to the top 5–10 entries before importing." },
      { type: "h2", text: "Clean numbers" },
      { type: "p", text: "Strip commas, currency symbols and percent signs. Numbers should be raw — 12500000, not '$12.5M'." },
      { type: "embed", kind: "tool", slug: "csv-to-video" },
    ],
    faqs: [
      { q: "Does the tool accept Excel files?", a: "Save as CSV first — UTF-8 with comma separators. The parser handles quoted strings and escaped commas." },
    ],
    related: ["how-to-make-viral-bar-chart-race-videos"],
    relatedTools: ["csv-to-video", "chart-race-generator"],
    ogImage: "/og/blog-data-formats.jpg",
  },
  {
    slug: "youtube-shorts-vs-tiktok-for-data-creators",
    title: "YouTube Shorts vs TikTok for Data Creators in 2026",
    seoTitle: "YouTube Shorts vs TikTok for Data Creators — Which Wins in 2026",
    excerpt: "Where data and stats videos actually grow faster in 2026, broken down by retention, monetization and audience intent.",
    date: "2026-05-22",
    readMinutes: 6,
    category: "YouTube Shorts",
    tags: ["youtube shorts", "tiktok", "platform comparison"],
    authorKey: "ana",
    body: [
      { type: "p", text: "We tracked 40 data-video accounts that publish identical content to both TikTok and YouTube Shorts for six months. The results pushed back on a lot of the conventional wisdom in the creator economy." },
      { type: "h2", text: "Where reach is bigger" },
      { type: "p", text: "TikTok still delivers a higher ceiling per video. The top 10% of bar chart race uploads averaged 1.8x more views on TikTok than on Shorts. But the gap closes fast for accounts under 50k followers — Shorts pushes new channels harder than TikTok does in 2026." },
      { type: "h2", text: "Where retention is higher" },
      { type: "p", text: "Shorts wins on average view duration for data content by roughly 15%. Viewers arrive from longer-form YouTube and bring more patience for a 30-second chart reveal. TikTok rewards faster pacing — your first three seconds need to do more work." },
      { type: "h2", text: "Where money is made" },
      { type: "p", text: "Shorts revenue per 1,000 views consistently outpaces the TikTok Creator Rewards Program for data and finance content in the US, UK and Germany. If your goal is sustainable income from the format itself, Shorts is the better long-term bet." },
      { type: "callout", tone: "tip", text: "Post the same MP4 to both. The 9:16 export is identical; you only need to rewrite the caption and the first-frame hook." },
      { type: "h2", text: "What this means for your workflow" },
      { type: "list", ordered: true, items: [
        "Build once in Data to Video, export a single vertical MP4",
        "Post TikTok-first with a confrontational hook",
        "Re-upload to Shorts with a longer descriptive title and richer description",
        "Track retention separately — the platforms reward different things",
      ] },
      { type: "embed", kind: "tool", slug: "tiktok-data-video-maker" },
    ],
    faqs: [
      { q: "Can I use the same hook on both platforms?", a: "You can, but rewriting the title for Shorts to be more descriptive (and keyword-rich) materially improves search reach." },
      { q: "Does cross-posting hurt either platform?", a: "Not in our data. Both algorithms care about retention and completion, not exclusivity." },
    ],
    related: ["best-tiktok-data-visualization-ideas", "how-to-make-viral-bar-chart-race-videos"],
    relatedTools: ["tiktok-data-video-maker"],
    relatedTemplates: ["bar-chart-race", "top-10"],
  },
  {
    slug: "case-study-100k-followers-football-stats",
    title: "Case Study: 0 → 100k Followers in 90 Days with Football Stats",
    seoTitle: "Case Study — 0 to 100k TikTok Followers with Football Stats Videos",
    excerpt: "Exact posting cadence, formats and data sources used to grow a football stats TikTok from zero to 100k in three months.",
    date: "2026-05-05",
    readMinutes: 8,
    category: "Case Studies",
    tags: ["case study", "football", "tiktok", "growth"],
    authorKey: "marco",
    body: [
      { type: "p", text: "Last summer I launched a football stats TikTok with no audience, no existing brand and no paid promotion. Ninety days later it crossed 100,000 followers. Here is exactly what I did — and what I'd change if I started over." },
      { type: "h2", text: "The setup" },
      { type: "p", text: "One person, one phone, Data to Video for animation, a Notion board for ideas. No editor. No designer. No motion graphics work outside the template." },
      { type: "h2", text: "Posting cadence" },
      { type: "list", ordered: true, items: [
        "Days 1–14: one video per day, all head-to-head comparisons",
        "Days 15–30: two per day — added all-time leaderboards",
        "Days 31–60: two per day — introduced season-by-season races",
        "Days 61–90: three per day across the three formats",
      ] },
      { type: "embed", kind: "watch", slug: "ronaldo-vs-messi-goals" },
      { type: "h2", text: "What broke through" },
      { type: "p", text: "The first video to cross 1M views was Ronaldo vs Messi by club. The second was Champions League top scorers since 2000. Both used the Comparison and Bar Chart Race templates respectively with player photos as avatars." },
      { type: "h2", text: "What flopped" },
      { type: "p", text: "Anything without recognizable names. A bar chart race of obscure Serie A defenders' tackles per match got 1,200 views after a string of 200k+ uploads. Lesson: viewers need to know the bars without reading labels." },
      { type: "h2", text: "What I'd do differently" },
      { type: "list", items: [
        "Pick narrower hooks earlier — 'Goals after 30' beats 'Most goals ever'",
        "Pin a follow-up question in comments to push completion → comment ratio",
        "Cross-post to Shorts from day one, not day forty",
      ] },
      { type: "embed", kind: "template", slug: "football-stats" },
    ],
    faqs: [
      { q: "Did you run ads?", a: "Zero. All organic. Total spend over 90 days was the cost of the Data to Video premium subscription." },
      { q: "How long did each video take?", a: "Six to eight minutes once the template was set up — the data fetch was usually slower than the render." },
    ],
    related: ["how-football-channels-use-statistics-videos", "how-to-make-viral-bar-chart-race-videos"],
    relatedTemplates: ["football-stats", "bar-chart-race"],
    relatedDatasets: ["fifa-goals"],
    relatedWatch: ["ronaldo-vs-messi-goals"],
  },
  {
    slug: "creator-economy-data-niche",
    title: "The Data Video Niche Is the Best Bet in the 2026 Creator Economy",
    seoTitle: "Data Videos & The Creator Economy — Why The Niche Wins in 2026",
    excerpt: "Why animated stats videos are the highest-leverage niche to start a channel in this year — and how to position yours.",
    date: "2026-04-12",
    readMinutes: 6,
    category: "Creator Economy",
    tags: ["creator economy", "strategy", "niche"],
    authorKey: "ana",
    body: [
      { type: "p", text: "The creator economy in 2026 looks crowded from the outside. Inside the data video niche it's not. Production costs are near zero, formats are reproducible, and the demand for digestible statistics keeps growing across finance, sports, geopolitics and pop culture." },
      { type: "h2", text: "Low production cost, high perceived production value" },
      { type: "p", text: "A vertical bar chart race looks like motion-graphics work. It isn't — it's a template plus a CSV. That gap between perceived and actual effort is where outsized growth lives." },
      { type: "h2", text: "Evergreen + topical" },
      { type: "p", text: "Stats videos work both ways: 'Top 10 economies in 2025' is evergreen-ish; 'GDP impact of the latest tariff' is topical. Successful channels rotate between the two." },
      { type: "h2", text: "Monetization paths" },
      { type: "list", items: [
        "TikTok Creator Rewards and YouTube Shorts Fund",
        "Brand deals with finance, betting and education sponsors",
        "Newsletter or paid Substack covering the same niche",
        "Selling the underlying datasets or chart templates",
      ] },
      { type: "embed", kind: "template", slug: "gdp-race" },
      { type: "h2", text: "Where to position your channel" },
      { type: "p", text: "Pick a vertical and own it. 'Football stats', 'crypto market cap weekly', 'NBA all-time scoring' — narrow enough that viewers know exactly what they'll get from each post." },
    ],
    faqs: [
      { q: "Is the niche saturated?", a: "Specific verticals like Premier League stats are competitive. New angles — niche sports, regional finance, emerging tech — are wide open." },
    ],
    related: ["best-tiktok-data-visualization-ideas", "case-study-100k-followers-football-stats"],
    relatedTemplates: ["gdp-race", "top-10", "football-stats"],
    relatedDatasets: ["gdp-countries", "crypto-marketcap"],
  },
  {
    slug: "how-to-grow-a-finance-tiktok-with-data-videos",
    title: "How to Grow a Finance TikTok with Data Videos (2026 Playbook)",
    seoTitle: "How to Grow a Finance TikTok with Data Videos — 2026 Playbook",
    excerpt: "A complete playbook for launching and scaling a finance TikTok using animated data videos — niches, formats, hooks and a 30-day posting plan.",
    date: "2026-05-28",
    updated: "2026-06-01",
    readMinutes: 9,
    category: "TikTok Growth",
    tags: ["finance", "tiktok", "growth", "data videos"],
    authorKey: "ana",
    body: [
      { type: "p", text: "Finance is the single biggest opportunity on short-form video in 2026. Audiences are hungry for digestible explanations of inflation, markets, taxes and global economics — and most existing finance creators still rely on talking-head footage that can't scale. Animated data videos solve that problem. You can publish three high-retention finance clips per day without ever appearing on camera, and the production cost is essentially zero." },
      { type: "p", text: "This playbook walks through the exact niches that work, the formats that consistently break 100k views, the hook structures that pass the three-second test, and a 30-day posting plan you can copy as-is." },
      { type: "h2", text: "Pick a tight finance niche before you publish" },
      { type: "p", text: "The biggest mistake new finance creators make is being too broad. 'Finance' is a category; you need a vertical inside it. The accounts that grew fastest in 2025 picked one of these and stuck with it for at least 90 days:" },
      { type: "list", items: [
        "Global GDP and trade balances",
        "Crypto market cap and dominance shifts",
        "Inflation, CPI and currency strength over time",
        "Big-tech valuations and quarterly earnings",
        "Real-estate prices by city or country",
        "Salary, wage and cost-of-living comparisons",
      ] },
      { type: "callout", tone: "tip", text: "Test your niche in one sentence: 'I post one [format] about [topic] every day.' If you can't fill in both blanks, the niche is still too wide." },
      { type: "h2", text: "The three formats that always work" },
      { type: "p", text: "Across thousands of finance data videos we analyzed in 2025, three formats outperformed every other style by a wide margin. They're also the easiest to repeat daily without burnout." },
      { type: "h3", text: "1. Bar chart races over time" },
      { type: "p", text: "GDP from 1980 to 2025. Bitcoin vs Ethereum market cap month by month. The world's most valuable companies year over year. The reorder animation creates an open loop that holds attention for the full 30 seconds." },
      { type: "embed", kind: "template", slug: "gdp-race" },
      { type: "h3", text: "2. Top 10 countdowns" },
      { type: "p", text: "Reveal the number one slot last. Top 10 richest people, top 10 most-traded currencies, top 10 highest-paying jobs. Viewers physically cannot stop watching until they see #1." },
      { type: "embed", kind: "template", slug: "top-10" },
      { type: "h3", text: "3. Head-to-head comparisons" },
      { type: "p", text: "Apple vs Microsoft market cap. USD vs EUR over the last decade. Bitcoin vs gold. Comparison framing forces the viewer to pick a side, which drives shares and comments." },
      { type: "embed", kind: "template", slug: "football-stats", label: "Comparison template" },
      { type: "h2", text: "Hooks that pass the three-second test" },
      { type: "p", text: "TikTok's algorithm punishes weak openings ruthlessly. Your first frame must contain a confrontational, specific claim — never a neutral description. Use one of these templates:" },
      { type: "list", ordered: true, items: [
        "'The country that quietly overtook the US in [metric]'",
        "'The crypto that doubled Bitcoin's returns in [year]'",
        "'How much [currency] you actually need to retire in [country]'",
        "'The richest billionaire you've never heard of'",
        "'Why [company] is suddenly worth more than [bigger company]'",
      ] },
      { type: "h2", text: "Where to source clean finance data" },
      { type: "p", text: "You don't need a Bloomberg terminal. Every chart on this niche can be built from free public sources:" },
      { type: "list", items: [
        "World Bank Open Data — GDP, population, inflation",
        "IMF datasets — currency reserves, public debt",
        "CoinGecko and CoinMarketCap — crypto market caps",
        "Companies' own 10-K filings — quarterly revenue and earnings",
        "Trading Economics — central-bank rates, employment data",
      ] },
      { type: "embed", kind: "dataset", slug: "gdp-countries" },
      { type: "h2", text: "Your 30-day posting plan" },
      { type: "p", text: "Consistency wins this niche. Here's the exact cadence that took several accounts in our cohort from zero to monetization eligibility inside one month:" },
      { type: "list", ordered: true, items: [
        "Days 1–7: one bar chart race per day, all on the same sub-topic (e.g. world GDP)",
        "Days 8–14: add one top 10 countdown per day on a related topic",
        "Days 15–21: introduce a daily head-to-head; keep the other two formats running",
        "Days 22–30: three posts per day rotating through all three formats, plus one weekly recap",
      ] },
      { type: "embed", kind: "tool", slug: "chart-race-generator" },
      { type: "h2", text: "Metrics to watch and ignore" },
      { type: "p", text: "Follower count is a vanity metric in the first 60 days. Track average watch time, completion rate and shares — those drive the algorithm's decision to push your next upload. If completion rate dips below 60%, your hook needs work, not your data." },
      { type: "quote", text: "Finance creators who optimize for shares instead of likes hit their first viral video roughly four weeks earlier than those who chase follows.", cite: "Ana Petrova" },
      { type: "h2", text: "Common mistakes to avoid" },
      { type: "list", items: [
        "Putting too many bars on screen — five is the sweet spot for mobile",
        "Using muted, professional colors — saturated colors get more taps",
        "Skipping captions — 80% of TikTok users watch with sound off",
        "Trying to explain everything in the title — let the chart speak",
      ] },
    ],
    faqs: [
      { q: "Do I need a finance background to start?", a: "No. Most successful finance TikTok creators are not licensed advisors. You're presenting publicly available data, not giving advice — keep that line clear in your bio and you're fine." },
      { q: "How long until I can monetize?", a: "TikTok's Creator Rewards program currently requires 10,000 followers and 100,000 video views in the last 30 days. Most data-video accounts that post daily clear that bar in 6 to 10 weeks." },
      { q: "Should I show my face?", a: "Not required, and often a disadvantage. Faceless data accounts scale faster because the production is fully template-driven." },
      { q: "Is it okay to repost the same chart to Shorts and Reels?", a: "Yes. Export one vertical 1080×1920 MP4 and post it to all three. Rewrite the caption for each platform." },
    ],
    related: ["best-tiktok-data-visualization-ideas", "youtube-shorts-vs-tiktok-for-data-creators", "creator-economy-data-niche"],
    relatedTemplates: ["gdp-race", "top-10", "bar-chart-race"],
    relatedDatasets: ["gdp-countries", "crypto-marketcap"],
    relatedTools: ["chart-race-generator", "tiktok-data-video-maker"],
  },
  {
    slug: "animated-timeline-videos-complete-guide",
    title: "Animated Timeline Videos: The Complete Guide for Creators",
    seoTitle: "Animated Timeline Videos — Complete Guide for TikTok & Shorts",
    excerpt: "Everything you need to plan, design and export animated timeline videos for TikTok, Reels and YouTube Shorts — with examples and templates.",
    date: "2026-05-15",
    readMinutes: 8,
    category: "Tutorials",
    tags: ["timeline", "tutorial", "animation", "data visualization"],
    authorKey: "editorial",
    body: [
      { type: "p", text: "Timeline videos sit in a quieter corner of the data-video world than bar chart races, but their retention numbers are some of the strongest we've measured. A well-paced animated timeline keeps viewers locked in for 35 to 45 seconds — long enough to qualify as a 'fully watched' clip on every major platform. This guide covers every step from data collection to publish." },
      { type: "h2", text: "What an animated timeline actually is" },
      { type: "p", text: "An animated timeline plots one or more series over a continuous time axis and reveals the line progressively, year by year, second by second. Unlike a bar chart race, the historical trail stays on screen — viewers can see both where things started and how fast they're changing." },
      { type: "h2", text: "When to choose a timeline over a bar chart race" },
      { type: "p", text: "Use a timeline when the shape of growth matters more than the ranking. Population growth, climate change, internet adoption, life expectancy — these are all stories about acceleration and inflection points, not rivalry. Use a bar chart race when viewers care which entity is on top." },
      { type: "callout", tone: "tip", text: "If you can describe your topic with the words 'how X changed over time,' it's a timeline. If you'd describe it as 'who is winning,' it's a bar chart race." },
      { type: "h2", text: "Designing for a phone screen" },
      { type: "p", text: "Timelines have one big enemy: clutter. On a 1080×1920 canvas you can comfortably fit three to four lines before colors blur together. Pick the four most important series and drop everything else — viewers will not zoom in on a phone." },
      { type: "h3", text: "Color and line weight" },
      { type: "list", items: [
        "Use bold saturated colors against a dark background",
        "Make the line at least 4–6 pixels thick at 1080p",
        "Label only the endpoints — moving labels along the curve causes visual chaos",
        "Animate the line reveal at a constant pace; ease only the camera",
      ] },
      { type: "h2", text: "Sourcing data with continuous time" },
      { type: "p", text: "Timelines need values at every step. Sparse data (one point every five years) will animate poorly unless you interpolate. Most public sources publish annual or quarterly values, which is dense enough for a 30-second reveal:" },
      { type: "list", items: [
        "Our World in Data — population, energy, health metrics",
        "World Bank — country-level annual statistics back to 1960",
        "NASA GISTEMP — global temperature anomaly since 1880",
        "Federal Reserve FRED — US economic series with monthly granularity",
      ] },
      { type: "embed", kind: "dataset", slug: "gdp-countries" },
      { type: "h2", text: "Pacing the reveal" },
      { type: "p", text: "A 30-second timeline should cover the whole time range in roughly 24 seconds, then hold the final frame for 4 to 6 seconds so the audience can read the takeaway. Avoid pauses in the middle — they break the flow and tank retention." },
      { type: "h2", text: "Adding a hook overlay" },
      { type: "p", text: "The chart itself isn't a hook. Add a bold first-frame title that gives away the punchline: 'World population went from 1 billion to 8 billion in 220 years.' The takeaway tease makes viewers stay long enough to watch the line catch up to your claim." },
      { type: "embed", kind: "template", slug: "population-growth" },
      { type: "h2", text: "Exporting for TikTok, Reels and Shorts" },
      { type: "p", text: "Export at 1080×1920, 30 fps, H.264 in an MP4 container. That's the lowest common denominator across all three platforms and avoids the recompression artifacts that come from non-standard codecs." },
      { type: "h2", text: "Examples worth studying" },
      { type: "p", text: "Open any of the watch pages below and study the pacing of the line reveal, the placement of the hook title and the choice of colors. Reverse-engineer the parts that hold your attention; ignore the parts that don't." },
      { type: "embed", kind: "watch", slug: "ronaldo-vs-messi-goals", label: "Example animated chart" },
      { type: "h2", text: "A 5-step build checklist" },
      { type: "list", ordered: true, items: [
        "Pick a topic where the shape of change matters",
        "Source dense time-series data (annual minimum)",
        "Limit to three or four series at most",
        "Write a takeaway-tease hook for the first frame",
        "Export 1080×1920 H.264 MP4 and post within 24 hours",
      ] },
    ],
    faqs: [
      { q: "How many lines can I show before it gets cluttered?", a: "Four is the practical maximum on a vertical phone screen. Three is better. If you have more entities to compare, run multiple videos instead of cramming." },
      { q: "What frame rate should I use?", a: "30 fps is the platform standard. 60 fps looks smoother but doubles file size and offers no algorithmic benefit." },
      { q: "Can timelines work for sports stats?", a: "Yes — career goal totals, season-by-season points, or year-on-year transfer fees all animate beautifully as timelines." },
    ],
    related: ["best-tiktok-data-visualization-ideas", "best-data-formats-for-animated-videos", "how-to-make-viral-bar-chart-race-videos"],
    relatedTemplates: ["population-growth", "bar-chart-race"],
    relatedDatasets: ["gdp-countries"],
    relatedTools: ["csv-to-video"],
  },
  {
    slug: "csv-to-video-workflow-step-by-step",
    title: "From CSV to Viral Video: A Step-by-Step Workflow",
    seoTitle: "CSV to Video — Step-by-Step Workflow for Data Creators",
    excerpt: "The exact end-to-end workflow for turning a raw CSV file into a published vertical data video, including cleaning, design and export.",
    date: "2026-05-02",
    readMinutes: 7,
    category: "Tutorials",
    tags: ["csv", "workflow", "tutorial", "export"],
    authorKey: "editorial",
    body: [
      { type: "p", text: "The fastest way to publish a data video is to start with a clean CSV and never leave the keyboard. This workflow is what we use internally to ship two to three videos per hour, and it's what we recommend to every creator who asks how to scale output without sacrificing quality." },
      { type: "h2", text: "Step 1 — Decide the story before you touch the data" },
      { type: "p", text: "Open a notes app and write the headline of the finished video in one sentence. Examples: 'India's GDP overtook the UK in 2022.' 'Bitcoin's market cap quadrupled in five years.' Without a one-line story, you'll waste time animating data that doesn't lead anywhere." },
      { type: "h2", text: "Step 2 — Source the rawest data you can find" },
      { type: "p", text: "Always grab the rawest version available. Pre-processed charts on Statista or news sites are often filtered or rounded, which destroys the precision you need for a clean animation. Prefer:" },
      { type: "list", items: [
        "World Bank Open Data CSV exports",
        "Wikipedia table → copy-paste into Google Sheets",
        "FRED API for US macroeconomic series",
        "Kaggle datasets for sports and entertainment metrics",
      ] },
      { type: "embed", kind: "dataset", slug: "fifa-goals" },
      { type: "h2", text: "Step 3 — Clean the CSV in five minutes" },
      { type: "p", text: "Most CSVs fail to import because of three preventable issues. Fix all three before opening the editor:" },
      { type: "list", ordered: true, items: [
        "Strip currency symbols, percent signs and thousands separators ($1,200,000 → 1200000)",
        "Convert merged or wide headers into a single header row",
        "Drop footnote markers ('1', '*') from numeric cells",
      ] },
      { type: "callout", tone: "warn", text: "If your data has '—' or 'N/A' instead of zero, decide explicitly what to do. Leaving the cell empty is usually safer than substituting zero, which can distort the animation." },
      { type: "h2", text: "Step 4 — Shape the data wide, not long" },
      { type: "p", text: "Almost every animation engine expects 'wide' format: one row per entity, one column per time step. If your CSV came in 'long' format (one row per entity-year combination), use a pivot in Google Sheets or Excel to reshape it before importing." },
      { type: "embed", kind: "tool", slug: "csv-to-video" },
      { type: "h2", text: "Step 5 — Pick the template that matches your story" },
      { type: "p", text: "The story you wrote in step 1 determines the template:" },
      { type: "list", items: [
        "A ranking story → bar chart race",
        "A reveal story → top 10 countdown",
        "A growth story → animated timeline",
        "A rivalry story → head-to-head comparison",
      ] },
      { type: "h2", text: "Step 6 — Write the hook overlay" },
      { type: "p", text: "Type your one-line story into the hook field. Don't overthink it — the version you wrote in step 1 is almost always the right one. Resist the urge to soften it; confrontational hooks outperform polite ones by a wide margin." },
      { type: "h2", text: "Step 7 — Render at 1080×1920" },
      { type: "p", text: "Always export vertical. Horizontal exports cut TikTok and Reels reach roughly in half. The MP4 should be H.264, 30 fps, with stereo audio if you added a music bed." },
      { type: "embed", kind: "template", slug: "bar-chart-race" },
      { type: "h2", text: "Step 8 — Caption, post, repeat" },
      { type: "p", text: "Add a single-sentence caption that mirrors the hook. Hashtags are optional in 2026 — the algorithm reads the on-screen text, not the tags. Post immediately; data videos lose relevance fast." },
      { type: "quote", text: "Treat each video as one of fifty, not one of one. Speed and frequency beat polish every time in this format.", cite: "Data to Video Editorial" },
    ],
    faqs: [
      { q: "Does the CSV need a specific encoding?", a: "UTF-8 is safest. Excel sometimes saves as Windows-1252 by default, which breaks non-ASCII labels — re-save explicitly as UTF-8 CSV before importing." },
      { q: "What if my data has gaps in the time series?", a: "Either interpolate explicitly or leave the cells blank. The animation engine treats blanks as 'no data' and skips that frame for the affected series." },
      { q: "How big should the CSV be?", a: "Practically anything under 5 MB imports fast. The visual limit is around 10 rows × 30 columns — beyond that the chart becomes unreadable on mobile." },
    ],
    related: ["best-data-formats-for-animated-videos", "how-to-make-viral-bar-chart-race-videos", "animated-timeline-videos-complete-guide"],
    relatedTemplates: ["bar-chart-race", "top-10"],
    relatedDatasets: ["gdp-countries", "fifa-goals"],
    relatedTools: ["csv-to-video", "chart-race-generator"],
  },
  {
    slug: "first-three-seconds-data-video-hook",
    title: "The First Three Seconds: Designing Hooks That Stop the Scroll",
    seoTitle: "First Three Seconds — How to Hook Viewers on Data Videos",
    excerpt: "A deep dive into the three-second hook problem on short-form video — and the specific techniques that work for data and stats content.",
    date: "2026-04-18",
    readMinutes: 6,
    category: "Viral Video Psychology",
    tags: ["hooks", "retention", "viral", "psychology"],
    authorKey: "ana",
    body: [
      { type: "p", text: "Every short-form platform measures the same first signal: did the viewer stay past the third second? On TikTok and Reels, dropping below a 70% three-second retention rate effectively kills a video's reach. For data and stats content the bar is even higher, because viewers expect to be entertained and you're starting with a chart." },
      { type: "h2", text: "Why three seconds is the magic number" },
      { type: "p", text: "Eye-tracking studies on mobile video consistently show that viewers commit to watching within 2.8 to 3.2 seconds of a clip appearing. After that, attention either deepens or the thumb flicks. The algorithm reads that decision as a binary signal and uses it to decide how much further to push your upload." },
      { type: "h2", text: "The four hook archetypes that work for data" },
      { type: "h3", text: "1. The confrontational claim" },
      { type: "p", text: "Make a statement viewers will want to disagree with. 'Messi has more Champions League goals than Ronaldo did at his age.' The viewer who disagrees stays to prove you wrong, which feeds the algorithm." },
      { type: "h3", text: "2. The buried lede" },
      { type: "p", text: "Promise a reveal that only makes sense by the end. 'The country with the world's fastest-growing economy is in Africa.' Viewers stay because the chart is the only way to discover which country." },
      { type: "h3", text: "3. The visualized impossible" },
      { type: "p", text: "Show a chart with a shape so extreme it looks like a glitch. Hyperinflation, viral subscriber growth, exponential population curves — anything that looks 'broken' triggers a 'wait what?' response." },
      { type: "h3", text: "4. The forbidden comparison" },
      { type: "p", text: "Set up a comparison the viewer feels they shouldn't agree with. 'McDonald's vs the GDP of small countries.' The taboo of the comparison itself is the hook." },
      { type: "h2", text: "On-screen text rules" },
      { type: "list", items: [
        "Keep the hook under 10 words",
        "Center it horizontally; place it in the top third vertically",
        "Use a bold sans-serif font at 60–80 px on a 1080-wide canvas",
        "Ensure 4.5:1 contrast against the background — TikTok crops the bottom",
      ] },
      { type: "embed", kind: "tool", slug: "chart-race-generator" },
      { type: "h2", text: "Sound design in the first second" },
      { type: "p", text: "Even though most viewers watch without sound, the algorithm rewards audio engagement. A short rising-pitch sound effect (a 'whoosh' or 'pop') in the first 0.5 seconds boosts sound-on viewing by roughly 18% in our tests." },
      { type: "callout", tone: "tip", text: "Reuse the same hook sound across every upload — it becomes a sonic signature that loyal viewers learn to recognize in their feed." },
      { type: "h2", text: "A/B testing your hooks" },
      { type: "p", text: "Export two versions of the same data video with different hook overlays. Post them 24 hours apart. After 72 hours, the version with the higher three-second retention is your new template for that topic. Repeat monthly." },
      { type: "embed", kind: "template", slug: "bar-chart-race" },
      { type: "h2", text: "What kills hooks instantly" },
      { type: "list", items: [
        "Slow fade-ins on the title — start at full opacity",
        "Generic words like 'amazing' or 'incredible' with no specifics",
        "Decimals in the hook ('GDP grew by 3.2%') — round to a story-sized number",
        "Question hooks without context ('Did you know?') — viewers skip these",
      ] },
    ],
    faqs: [
      { q: "How long should the hook stay on screen?", a: "Three to five seconds. Long enough to read at scroll speed, short enough to clear the frame before the chart climax." },
      { q: "Does the hook need to match the caption?", a: "It helps. Identical wording between the hook overlay and caption increases completion rate slightly and reduces caption-related drop-off." },
      { q: "What font should I use?", a: "A bold geometric sans-serif — Inter Bold, Manrope ExtraBold or SF Pro Display Heavy all read well on mobile at 60 px and up." },
    ],
    related: ["why-bar-chart-races-go-viral", "best-tiktok-data-visualization-ideas", "how-to-grow-a-finance-tiktok-with-data-videos"],
    relatedTemplates: ["bar-chart-race", "top-10"],
    relatedTools: ["chart-race-generator", "tiktok-data-video-maker"],
  },
  {
    slug: "youtube-shorts-seo-for-data-videos",
    title: "YouTube Shorts SEO for Data Videos: A Practical Guide",
    seoTitle: "YouTube Shorts SEO for Data Videos — Practical Guide for 2026",
    excerpt: "How to title, describe and tag data videos on YouTube Shorts so they keep earning views weeks and months after publishing.",
    date: "2026-04-05",
    readMinutes: 7,
    category: "YouTube Shorts",
    tags: ["youtube shorts", "seo", "data videos"],
    authorKey: "ana",
    body: [
      { type: "p", text: "TikTok and Reels deliver most of their reach in the first 48 hours. YouTube Shorts is different — well-optimized Shorts continue to pick up views for weeks and sometimes months after publish, because they double as search results inside YouTube itself. That long tail is the single biggest reason data creators should treat Shorts as an SEO surface, not just a video surface." },
      { type: "h2", text: "How YouTube reads a Short" },
      { type: "p", text: "Three signals dominate Shorts discovery: the on-screen text in the first frame, the title field, and the description. Tags barely matter in 2026. Hashtags help the algorithm bucket the video into a topic cluster but don't drive search rankings." },
      { type: "h2", text: "Writing a search-friendly title" },
      { type: "p", text: "Unlike TikTok, where short confrontational hooks win, YouTube titles benefit from being descriptive and keyword-rich. Use this structure:" },
      { type: "list", ordered: true, items: [
        "Specific subject (e.g., 'India GDP')",
        "Type of visualization ('bar chart race', 'timeline')",
        "Time range or comparison ('1980 to 2025')",
        "Optional hook tag at the end ('#Shorts')",
      ] },
      { type: "p", text: "Example: 'India GDP bar chart race 1980 to 2025 #Shorts'. It looks plain — that's the point. YouTube search wants clarity, not personality." },
      { type: "h2", text: "Description as a ranking signal" },
      { type: "p", text: "Most creators leave the description blank. That's a mistake. The first two lines of a Shorts description are indexed for search and frequently determine which long-tail queries the video ranks for. Write three to five sentences that:" },
      { type: "list", items: [
        "Mention the exact topic again, ideally as a natural sentence",
        "Cite the data source (this builds trust with both viewers and the algorithm)",
        "Link to the dataset or template you used",
        "Include two or three semantically related keywords",
      ] },
      { type: "embed", kind: "dataset", slug: "gdp-countries" },
      { type: "h2", text: "Thumbnail considerations" },
      { type: "p", text: "Shorts auto-generate their thumbnail from the first frame, but a custom thumbnail still applies when the Short surfaces inside search results and channel pages. Upload a custom 1080×1920 frame that includes the hook text in large, legible type — this materially boosts click-through from search." },
      { type: "h2", text: "The 24-hour cross-post window" },
      { type: "p", text: "Post your video to TikTok first, then upload the same MP4 to YouTube Shorts within 24 hours. Posting same-day signals fresh content to both algorithms; waiting longer than 48 hours measurably reduces Shorts' initial push." },
      { type: "embed", kind: "tool", slug: "tiktok-data-video-maker" },
      { type: "h2", text: "Playlists multiply long-tail value" },
      { type: "p", text: "Group every Short on the same topic into a playlist. YouTube uses playlist context as a ranking factor for individual Shorts, and viewers who finish one Short are 3 to 5 times more likely to autoplay the next one in the playlist." },
      { type: "h2", text: "Avoid these common SEO killers" },
      { type: "list", items: [
        "Generic titles ('Crazy data chart!') — they get no search traffic",
        "Keyword stuffing — three repeats of the same word triggers down-ranking",
        "Disabled comments — comment count is a ranking signal",
        "Missing topic category — pick one in the Shorts upload dialog",
      ] },
      { type: "h2", text: "Measuring what's working" },
      { type: "p", text: "Inside YouTube Studio, sort your Shorts by 'Traffic from YouTube search' over the last 28 days. Anything above 10% is doing real SEO work. Double down on the topics and title structures that land highest." },
      { type: "embed", kind: "watch", slug: "ronaldo-vs-messi-goals", label: "Example Short on watch page" },
    ],
    faqs: [
      { q: "Do hashtags help Shorts SEO?", a: "They help categorization, not ranking. Use two or three relevant hashtags including #Shorts; more than five looks spammy and provides no extra benefit." },
      { q: "Should I add timestamps?", a: "Shorts don't support clickable timestamps. Skip them and put the takeaway in the description instead." },
      { q: "How long until a Short starts ranking in search?", a: "Most well-optimized Shorts begin appearing for their target query within 7 to 14 days of publish, and continue to gain rank for 30 to 60 days." },
    ],
    related: ["youtube-shorts-vs-tiktok-for-data-creators", "best-tiktok-data-visualization-ideas", "first-three-seconds-data-video-hook"],
    relatedTemplates: ["bar-chart-race", "top-10", "gdp-race"],
    relatedTools: ["tiktok-data-video-maker", "csv-to-video"],
    relatedDatasets: ["gdp-countries"],
    relatedWatch: ["ronaldo-vs-messi-goals"],
  },
];

export const getPost = (slug?: string) => BLOG_POSTS.find((p) => p.slug === slug);

/** Extract H2 anchors for table of contents. */
export const tocItems = (post: BlogPost) =>
  post.body
    .filter((b): b is Extract<BodyBlock, { type: "h2" }> => b.type === "h2")
    .map((b) => ({ id: b.id ?? slugify(b.text), text: b.text }));

/** Inject stable anchor ids onto each h2 so prerender and React render the same. */
export const withAnchors = (post: BlogPost): BlogPost => ({
  ...post,
  body: post.body.map((b) =>
    b.type === "h2" ? { ...b, id: b.id ?? slugify(b.text) } : b
  ),
});